# fly.toml file generated for quarterly-preview on 2021-12-01T22:23:08Z

app = "quarterly-preview"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/mikemoraned/quarterly-clock:0.1.0-amd64"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = "./server"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
